# dev
brew "bash"
brew "git"
brew "whalebrew"
brew "zsh"
cask "docker"
cask "font-meslo-lg-nerd-font"
cask "iterm2"
cask "tableplus"
cask "utm"

# go
brew "golang"
brew "golangci-lint"

# jetbrains
cask "clion"
cask "goland"
cask "intellij-idea-ce"
cask "jetbrains-toolbox"
cask "rubymine"

# c++
brew "cmake"
brew "gcc"
brew "llvm"
brew "make"

