return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  branch = "main",
  build = ":TSUpdate",
  config = function()
    require('nvim-treesitter').install({
      "c",
      "cpp",
      "css",
      "dockerfile",
      "gdscript",
      "gdshader",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "glsl",
      "go",
      "gomod",
      "gosum",
      "gotmpl",
      "gowork",
      "graphql",
      "helm",
      "html",
      "http",
      "java",
      "javascript",
      "jq",
      "json",
      "kotlin",
      "ledger",
      "llvm",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "perl",
      "python",
      "regex",
      "ruby",
      "rust",
      "scss",
      "sql",
      "ssh_config",
      "terraform",
      "toml",
      "tsv",
      "tsx",
      "typescript",
      "vim",
      "vue",
      "xml",
      "yaml",
    })
  end
}

