services:

  tailscale:
    container_name: tailscale
    hostname: apollo
    image: tailscale/tailscale:latest
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    volumes:
      - tailscale-state:/var/lib/tailscale
    environment:
      - TS_AUTHKEY=$TAILSCALE_AUTH_KEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false

  samba:
    container_name: samba
    build: ./samba
    restart: unless-stopped
    read_only: true
    ports:
      - 445:445/tcp
    volumes:
      - /mnt/vault:/media/vault
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro

  home-assistant:
    container_name: home-assistant
    image: lscr.io/linuxserver/homeassistant:latest
    restart: unless-stopped
    volumes:
      - home-assistant-config:/config
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - homebridge:/homebridge
    environment:
      - TZ=America/Los_Angeles
      - ENABLE_AVAHI=0

volumes:
  home-assistant-config:
  homebridge:
  tailscale-state:

