services:
  tailscale:
    container_name: tailscale
    hostname: apollo
    image: tailscale/tailscale:latest
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    volumes:
      - tailscale-state:/var/lib/tailscale
    environment:
      - TS_AUTHKEY=$TAILSCALE_AUTH_KEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false

  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:latest
    restart: unless-stopped
    volumes:
      - home-assistant-config:/config
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles

  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - homebridge:/homebridge
    environment:
      - TZ=America/Los_Angeles
      - ENABLE_AVAHI=0

  omada:
    container_name: omada
    image: mbentley/omada-controller:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - MANAGE_HTTP_PORT=8080
      - MANAGE_HTTPS_PORT=8043
      - PORTAL_HTTP_PORT=8081
      - PORTAL_HTTPS_PORT=8843
      - SHOW_SERVER_LOGS=true
      - SHOW_MONGODB_LOGS=false
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
      - omada-work:/opt/tplink/EAPController/work

volumes:
  home-assistant-config:
  homebridge:
  omada-data:
  omada-logs:
  omada-work:
  tailscale-state:
