services:
  samba:
    build: ./samba
    container_name: samba
    restart: unless-stopped
    ports:
      - 445:445/tcp
    volumes:
      - /mnt/vault:/media/vault
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro


