---
name: base apps
needs: rosetta # for rectangle
brew:
  brews:
    - dockutil
  casks:
    - 1password
    - 1password-cli
    - caffeine
    - firefox
    - google-chrome
    - mos
    - rectangle
  mas:
    - name: velja
      id: 1607635845

