-- require('lsp').configure_lsp('solargraph', {
--   cmd = { 'solargraph', 'stdio' },
--   settings = {
--     solargraph = {
--       diagnostics = true,
--     },
--   },
--   init_options = { formatting = true },
--   filetypes = { 'ruby' },
--   root_markers = { 'Gemfile', '.git' },
-- })
