# standard
brew "dockutil"
brew "fzf"
brew "mas"
cask "1password"
cask "1password-cli"
cask "caffeine"
cask "firefox"
cask "google-chrome"
cask "mos"
cask "rectangle"
mas "Velja", id: 1607635845

# productivity
cask "dropbox"
cask "notion"
cask "notion-calendar"
cask "openvpn-connect"
cask "postman"
cask "slack"
cask "zoom"
mas "Spark", id: 1176895641

# entertainment
cask "spotify"

# keyboard
cask "qmk-toolbox"
cask "via"

