# prereqs
brew "dockutil"
brew "mas"

# standard
cask "1password"
cask "google-chrome"
cask "mos"
cask "rectangle"

# productivity
cask "notion-calendar"
cask "slack"
cask "zoom"
mas "Spark", id: 1176895641

# entertainment
cask "spotify"

