# add extra bin directories to path
export PATH=/usr/local/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH=./bin:$PATH

# oh-my-zsh directory and config
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(brew git chruby ruby bundler rails npm heroku zsh-interactive-cd macos docker docker-compose)
source $ZSH/oh-my-zsh.sh

# load config directory
for f in $HOME/.zsh_profile.d/*.sh; do
  source $f
done

# load secrets (shhhhhh)
if [ -f $HOME/.secrets ]; then
  source $HOME/.secrets
fi

# load aliases
source $HOME/.zsh_aliases

# and display a nice banner
header
