# add extra bin directories to path
export PATH="/usr/local/bin:${PATH}"
export PATH="${HOME}/.local/bin:${PATH}"
export PATH="${HOME}/bin:${PATH}"
export PATH="./bin:${PATH}"

# oh-my-zsh directory and config
export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(brew git chruby ruby bundler rails npm heroku zsh-interactive-cd macos docker docker-compose)
source "${ZSH}/oh-my-zsh.sh"

# load config directory
for f in "${HOME}/.zsh_profile.d"/*.sh; do
  source "$f"
done

# load secrets (shhhhhh)
[[ -f "${HOME}/.secrets" ]] && source "${HOME}/.secrets"

# load aliases
source "${HOME}/.zsh_aliases"

# and display a nice banner
header

# override `cd` to run hooks in current directory (if applicable)
function cd {
  builtin cd "$@" || return 1
  [[ -f ./.cd_hook ]] && source ./.cd_hook || return 0
}
# finally, run any cd_hooks in the current dir
[[ -f ./.cd_hook ]] && source ./.cd_hook

