# put homebrew first in path
export PATH=/usr/local/bin:$PATH

# add user bin to path
export PATH="${HOME}"/bin:$PATH

# disable mac os catalina zsh warning
export BASH_SILENCE_DEPRECATION_WARNING=1

# eternal instant history (without duplicates)
# eternal history from (http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login)
# sync and duplicate handling from (https://unix.stackexchange.com/a/18443)
HISTFILE="/Users/${USER}/.bash_eternal_history"
HISTSIZE=
HISTFILESIZE=
HISTCONTROL=ignoredups:erasedups
shopt -s histappend
PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND"

# load bash aliases
[[ -f ~/.bash_aliases ]] && source ~/.bash_aliases

# load secret env variables!
[[ -f ~/.env ]] && source ~/.env

# add user bin to path
export PATH=~/bin:$PATH

# homebrew bash completion
[[ -f `brew --prefix`/etc/profile.d/bash_completion ]] && . `brew --prefix`/etc/profile.d/bash_completion

# make libssl visible to pkg-config
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

# load additional configs
for f in ~/.bash_profile.d/*.sh ; do
  source $f
done

# override `cd` to run hooks in current directory (if applicable)
function cd {
  builtin cd "$@" || return
  [[ -f .cd_hook ]] && . .cd_hook || return
}
[[ -f .cd_hook ]] && . .cd_hook

# sync iterm profile with OS dark mode setting
sync-dark-mode

# set prompt
[[ -f ~/.bash_prompt ]] && . ~/.bash_prompt

# finally, display welcome banner
header
